#include "Program.h"
#include "UILayout/MainMenu.h"
#include "UILayout/Settings.h"
#include "UILayout/ChooseDS.h"
#include "UILayout/VisSLL.h"
#include "UILayout/VisHashTable.h"
#include "UILayout/VisAVL.h"
